from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, List, Tuple, Optional
import itertools

from pymatgen.core.composition import Composition


@dataclass(frozen=True)
class Candidate:
    N: int
    reduced_formula: str
    unreduced_formula: str
    integer_reduced_composition: Composition
    integer_unreduced_composition: Composition
    frac: Dict[str, float]
    err_l1: float
    err_linf: float
    ion_guesses: List[Dict[str, float]]  


def _target_fraction(comp: Composition) -> Dict[str, float]:
    fc = comp.fractional_composition
    return {str(el): float(v) for el, v in fc.items()}


def _errors(target: Dict[str, float], got: Dict[str, float]) -> Tuple[float, float]:
    keys = sorted(set(target) | set(got))
    diffs = [abs(got.get(k, 0.0) - target.get(k, 0.0)) for k in keys]
    return (sum(diffs), max(diffs) if diffs else 0.0)


def unreduced_formula_str(comp: Composition, order: List[str]) -> str:
    d = comp.get_el_amt_dict()
    s = ""
    for el in order:
        if el not in d:
            continue
        n = int(round(d[el]))
        if n == 0:
            continue
        s += el if n == 1 else f"{el}{n}"
    return s


def _all_integer_tuples_sum_N(m: int, N: int):
    if m == 1:
        yield (N,)
        return
    for x in range(N + 1):
        for rest in _all_integer_tuples_sum_N(m - 1, N - x):
            yield (x,) + rest


def enumerate_ratio_formulas(
    fraction_formula: str,
    N: int,
    eps: float,
    metric: str = "linf",          # "linf" or "l1"
    max_candidate: int = 6,
    compute_ion_guesses: bool = True,      
    all_oxi_states: bool = False,          
    max_sites: Optional[int] = None,       
    oxi_states_override: Optional[dict] = None,  
) -> List[Candidate]:
    """
    Input:
      fraction_formula: e.g. "Ag0.33Cl0.67"
      N: total atom count (single value)
      eps: tolerance parameter (accept if err <= eps*N)
    Output:
      List[Candidate] that satisfy acceptance criterion.

    Acceptance:
      err = max_i |x_int_i - x_target_i|   (metric="linf")
      err = sum_i |x_int_i - x_target_i|   (metric="l1")
      accept if err <= eps * N
    """
    if N <= 0:
        return []

    target_comp = Composition(fraction_formula)
    target_frac = _target_fraction(target_comp)

    elems = list(target_frac.keys())
    m = len(elems)

    raw = [N * target_frac[e] for e in elems]
    floors = [int(x // 1) for x in raw]
    base_sum = sum(floors)
    need = N - base_sum

    candidates: List[Candidate] = []

    def add_candidate(counts: List[int]):
        if sum(counts) != N:
            return
        if all(c == 0 for c in counts):
            return

        int_comp = Composition({elems[i]: counts[i] for i in range(m) if counts[i] != 0})
        frac = _target_fraction(int_comp)
        err_l1, err_linf = _errors(target_frac, frac)
        err = err_linf if metric.lower() == "linf" else err_l1

        if err <= eps * N:
            red_comp = Composition(int_comp.reduced_formula)

            if compute_ion_guesses:
                ion_guesses = red_comp.oxi_state_guesses(
                    oxi_states_override=oxi_states_override,
                    all_oxi_states=all_oxi_states,
                    max_sites=max_sites,
                )
            else:
                ion_guesses = []

            candidates.append(
                Candidate(
                    N=N,
                    reduced_formula=int_comp.reduced_formula,
                    unreduced_formula=unreduced_formula_str(int_comp, elems),
                    integer_reduced_composition=red_comp,
                    integer_unreduced_composition=int_comp,
                    frac=frac,
                    err_l1=err_l1,
                    err_linf=err_linf,
                    ion_guesses=ion_guesses,
                )
            )

    if 0 <= need <= m:
        for idxs in itertools.combinations(range(m), need):
            counts = floors.copy()
            for i in idxs:
                counts[i] += 1
            add_candidate(counts)
    else:
        if m >= max_candidate:
            return []
        for counts in _all_integer_tuples_sum_N(m, N):
            add_candidate(list(counts))

    uniq = {}
    for c in candidates:
        key = c.unreduced_formula
        if key not in uniq or (c.err_linf, c.err_l1) < (uniq[key].err_linf, uniq[key].err_l1):
            uniq[key] = c

    out = sorted(uniq.values(), key=lambda x: (x.err_linf, x.err_l1, x.reduced_formula, x.unreduced_formula))
    return out

In [9]:
from intchem import enumerate_ratio_formulas

In [10]:
def test_enumerate_ratio_formulas(chemical_formula="Ag0.33Cl0.67", all_oxi_states=False, eps=0.02, N1=1, N2=12):
    import pandas as pd
    import pickle
    import os
    results = []
    for N in range(N1, N2+1):
        cands = enumerate_ratio_formulas(chemical_formula, N=N, eps=eps, metric="linf",all_oxi_states=all_oxi_states)
        for c in cands:
            results.append({
                "N": N,
                "unreduced_formula": c.unreduced_formula,
                "reduced_formula": c.reduced_formula,
                "error": c.err_linf,
                "ion_guesses": c.ion_guesses,
            })
    df = pd.DataFrame(results)
    dir_path = "data"
    filename = f"{dir_path}/{chemical_formula}.pickle"
    os.makedirs( dir_path, exist_ok=True)
    with open(filename,"wb") as f:
        pickle.dump(df,f)
    return df

test_enumerate_ratio_formulas(chemical_formula = "Ag0.33Cl0.67")

,N,unreduced_formula,reduced_formula,error,ion_guesses
0,3,AgCl2,AgCl2,0.003333,"({'Ag': 2.0, 'Cl': -1.0},)"
1,5,Ag2Cl3,Ag2Cl3,0.070000,"({'Ag': 1.5, 'Cl': -1.0},)"
2,6,Ag2Cl4,AgCl2,0.003333,"({'Ag': 2.0, 'Cl': -1.0},)"
3,7,Ag2Cl5,Ag2Cl5,0.044286,"({'Ag': 2.5, 'Cl': -1.0},)"
4,7,Ag3Cl4,Ag3Cl4,0.098571,"({'Ag': 1.3333333333333333, 'Cl': -1.0},)"
5,8,Ag3Cl5,Ag3Cl5,0.045000,"({'Ag': 1.6666666666666667, 'Cl': -1.0},)"
6,8,Ag2Cl6,AgCl3,0.080000,"({'Ag': 3.0, 'Cl': -1.0},)"
7,9,Ag3Cl6,AgCl2,0.003333,"({'Ag': 2.0, 'Cl': -1.0},)"
8,9,Ag2Cl7,Ag2Cl7,0.107778,()
9,10,Ag3Cl7,Ag3Cl7,0.030000,"({'Ag': 2.3333333333333335, 'Cl': -1.0},)"
10,10,Ag4Cl6,Ag2Cl3,0.070000,"({'Ag': 1.5, 'Cl': -1.0},)"
11,11,Ag4Cl7,Ag4Cl7,0.033636,"({'Ag': 1.75, 'Cl': -1.0},)"
12,11,Ag3Cl8,Ag3Cl8,0.057273,"({'Ag': 2.6666666666666665, 'Cl': -1.0},)"
13,12,Ag4Cl8,AgCl2,0.003333,"({'Ag': 2.0, 'Cl': -1.0},)"
14,12,Ag3Cl9,AgCl3,0.080000,"({'Ag': 3.0, 'Cl': -1.0},)"

In [11]:
test_enumerate_ratio_formulas(chemical_formula = "Na0.45Cl0.55")

     N unreduced_formula reduced_formula     error                 ion_guesses
0    4            Na2Cl2            NaCl  0.050000  ({'Na': 1.0, 'Cl': -1.0},)
1    5            Na2Cl3          Na2Cl3  0.050000                          ()
2    6            Na3Cl3            NaCl  0.050000  ({'Na': 1.0, 'Cl': -1.0},)
3    6            Na2Cl4           NaCl2  0.116667                          ()
4    7            Na3Cl4          Na3Cl4  0.021429                          ()
5    7            Na4Cl3          Na4Cl3  0.121429                          ()
6    8            Na4Cl4            NaCl  0.050000  ({'Na': 1.0, 'Cl': -1.0},)
7    8            Na3Cl5          Na3Cl5  0.075000                          ()
8    9            Na4Cl5          Na4Cl5  0.005556                          ()
9    9            Na5Cl4          Na5Cl4  0.105556                          ()
10  10            Na4Cl6          Na2Cl3  0.050000                          ()
11  10            Na5Cl5            NaCl  0.050000  ({'Na': 1.0, 'Cl': -1.0},)
12  11            Na5Cl6          Na5Cl6  0.004545                          ()
13  11            Na4Cl7          Na4Cl7  0.086364                          ()
14  12            Na5Cl7          Na5Cl7  0.033333                          ()
15  12            Na6Cl6            NaCl  0.050000  ({'Na': 1.0, 'Cl': -1.0},)

In [12]:
test_enumerate_ratio_formulas(chemical_formula = "Fe2O3")

,N,unreduced_formula,reduced_formula,error,ion_guesses
0,5,Fe2O3,Fe2O3,0.000000,"({'Fe': 3.0, 'O': -2.0},)"
1,6,Fe2O4,FeO2,0.066667,()
2,6,Fe3O3,FeO,0.100000,"({'Fe': 2.0, 'O': -2.0},)"
3,7,Fe3O4,Fe3O4,0.028571,"({'Fe': 2.6666666666666665, 'O': -2.0},)"
4,7,Fe2O5,Fe2O5,0.114286,()
5,8,Fe3O5,Fe3O5,0.025000,()
6,8,Fe4O4,FeO,0.100000,"({'Fe': 2.0, 'O': -2.0},)"
7,9,Fe4O5,Fe4O5,0.044444,"({'Fe': 2.5, 'O': -2.0},)"
8,9,Fe3O6,FeO2,0.066667,()
9,10,Fe4O6,Fe2O3,0.000000,"({'Fe': 3.0, 'O': -2.0},)"
10,11,Fe4O7,Fe4O7,0.036364,()
11,11,Fe5O6,Fe5O6,0.054545,"({'Fe': 2.4, 'O': -2.0},)"
12,12,Fe5O7,Fe5O7,0.016667,"({'Fe': 2.8, 'O': -2.0},)"
13,12,Fe4O8,FeO2,0.066667,()

In [13]:
test_enumerate_ratio_formulas(chemical_formula = "Fe3O4")

,N,unreduced_formula,reduced_formula,error,ion_guesses
0,4,Fe2O2,FeO,0.071429,"({'Fe': 2.0, 'O': -2.0},)"
1,5,Fe2O3,Fe2O3,0.028571,"({'Fe': 3.0, 'O': -2.0},)"
2,6,Fe3O3,FeO,0.071429,"({'Fe': 2.0, 'O': -2.0},)"
3,6,Fe2O4,FeO2,0.095238,()
4,7,Fe3O4,Fe3O4,0.000000,"({'Fe': 2.6666666666666665, 'O': -2.0},)"
5,8,Fe3O5,Fe3O5,0.053571,()
6,8,Fe4O4,FeO,0.071429,"({'Fe': 2.0, 'O': -2.0},)"
7,9,Fe4O5,Fe4O5,0.015873,"({'Fe': 2.5, 'O': -2.0},)"
8,9,Fe3O6,FeO2,0.095238,()
9,10,Fe4O6,Fe2O3,0.028571,"({'Fe': 3.0, 'O': -2.0},)"
10,10,Fe5O5,FeO,0.071429,"({'Fe': 2.0, 'O': -2.0},)"
11,11,Fe5O6,Fe5O6,0.025974,"({'Fe': 2.4, 'O': -2.0},)"
12,11,Fe4O7,Fe4O7,0.064935,()
13,12,Fe5O7,Fe5O7,0.011905,"({'Fe': 2.8, 'O': -2.0},)"
14,12,Fe6O6,FeO,0.071429,"({'Fe': 2.0, 'O': -2.0},)"

In [14]:
test_enumerate_ratio_formulas(chemical_formula = "Na2Cl3")

     N unreduced_formula reduced_formula     error                 ion_guesses
0    5            Na2Cl3          Na2Cl3  0.000000                          ()
1    6            Na2Cl4           NaCl2  0.066667                          ()
2    6            Na3Cl3            NaCl  0.100000  ({'Na': 1.0, 'Cl': -1.0},)
3    7            Na3Cl4          Na3Cl4  0.028571                          ()
4    7            Na2Cl5          Na2Cl5  0.114286                          ()
5    8            Na3Cl5          Na3Cl5  0.025000                          ()
6    8            Na4Cl4            NaCl  0.100000  ({'Na': 1.0, 'Cl': -1.0},)
7    9            Na4Cl5          Na4Cl5  0.044444                          ()
8    9            Na3Cl6           NaCl2  0.066667                          ()
9   10            Na4Cl6          Na2Cl3  0.000000                          ()
10  11            Na4Cl7          Na4Cl7  0.036364                          ()
11  11            Na5Cl6          Na5Cl6  0.054545                          ()
12  12            Na5Cl7          Na5Cl7  0.016667                          ()
13  12            Na4Cl8           NaCl2  0.066667                          ()

In [15]:
test_enumerate_ratio_formulas(chemical_formula = "Fe2O3")

,N,unreduced_formula,reduced_formula,error,ion_guesses
0,5,Fe2O3,Fe2O3,0.000000,"({'Fe': 3.0, 'O': -2.0},)"
1,6,Fe2O4,FeO2,0.066667,()
2,6,Fe3O3,FeO,0.100000,"({'Fe': 2.0, 'O': -2.0},)"
3,7,Fe3O4,Fe3O4,0.028571,"({'Fe': 2.6666666666666665, 'O': -2.0},)"
4,7,Fe2O5,Fe2O5,0.114286,()
5,8,Fe3O5,Fe3O5,0.025000,()
6,8,Fe4O4,FeO,0.100000,"({'Fe': 2.0, 'O': -2.0},)"
7,9,Fe4O5,Fe4O5,0.044444,"({'Fe': 2.5, 'O': -2.0},)"
8,9,Fe3O6,FeO2,0.066667,()
9,10,Fe4O6,Fe2O3,0.000000,"({'Fe': 3.0, 'O': -2.0},)"
10,11,Fe4O7,Fe4O7,0.036364,()
11,11,Fe5O6,Fe5O6,0.054545,"({'Fe': 2.4, 'O': -2.0},)"
12,12,Fe5O7,Fe5O7,0.016667,"({'Fe': 2.8, 'O': -2.0},)"
13,12,Fe4O8,FeO2,0.066667,()

In [16]:
test_enumerate_ratio_formulas(chemical_formula = "Nd2Fe14B")

     N unreduced_formula reduced_formula     error ion_guesses
0    5             NdFe4           NdFe4  0.082353          ()
1    6             NdFe5           NdFe5  0.058824          ()
2    6              Fe5B            Fe5B  0.117647          ()
3    7             NdFe6           NdFe6  0.058824          ()
4    7            NdFe5B          NdFe5B  0.109244          ()
5    7              Fe6B            Fe6B  0.117647          ()
6    8             NdFe7           NdFe7  0.058824          ()
7    8            NdFe6B          NdFe6B  0.073529          ()
8    8              Fe7B            Fe7B  0.117647          ()
9    9            NdFe7B          NdFe7B  0.052288          ()
10   9             NdFe8           NdFe8  0.065359          ()
11   9            Nd2Fe7          Nd2Fe7  0.104575          ()
12  10            NdFe8B          NdFe8B  0.041176          ()
13  10             NdFe9           NdFe9  0.076471          ()
14  10            Nd2Fe8           NdFe4  0.082353          ()
15  11            NdFe9B          NdFe9B  0.032086          ()
16  11            Nd2Fe9          Nd2Fe9  0.064171          ()
17  11            NdFe10          NdFe10  0.085561          ()
18  12           NdFe10B         NdFe10B  0.034314          ()
19  12           Nd2Fe10           NdFe5  0.058824          ()
20  12           Nd2Fe9B         Nd2Fe9B  0.073529          ()

In [17]:
test_enumerate_ratio_formulas(chemical_formula = "PbTiO3")

,N,unreduced_formula,reduced_formula,error,ion_guesses
0,5,PbTiO3,TiPbO3,0.000000,"({'Ti': 4.0, 'Pb': 2.0, 'O': -2.0}, {'Ti': 2.0..."
1,6,PbTiO4,TiPbO4,0.066667,"({'Ti': 4.0, 'Pb': 4.0, 'O': -2.0},)"
2,7,Pb2TiO4,Ti(PbO2)2,0.085714,"({'Ti': 4.0, 'Pb': 2.0, 'O': -2.0}, {'Ti': 2.0..."
3,7,PbTi2O4,Ti2PbO4,0.085714,"({'Ti': 3.0, 'Pb': 2.0, 'O': -2.0}, {'Ti': 2.0..."
4,7,PbTiO5,TiPbO5,0.114286,()
5,8,PbTi2O5,Ti2PbO5,0.075000,"({'Ti': 4.0, 'Pb': 2.0, 'O': -2.0}, {'Ti': 3.0..."
6,8,Pb2TiO5,TiPb2O5,0.075000,"({'Ti': 4.0, 'Pb': 3.0, 'O': -2.0}, {'Ti': 2.0..."
7,8,Pb2Ti2O4,TiPbO2,0.100000,"({'Ti': 2.0, 'Pb': 2.0, 'O': -2.0},)"
8,9,Pb2Ti2O5,Ti2Pb2O5,0.044444,"({'Ti': 3.0, 'Pb': 2.0, 'O': -2.0}, {'Ti': 2.0..."
9,9,Pb2TiO6,Ti(PbO3)2,0.088889,"({'Ti': 4.0, 'Pb': 4.0, 'O': -2.0},)"
10,9,PbTi2O6,Ti2PbO6,0.088889,"({'Ti': 4.0, 'Pb': 4.0, 'O': -2.0},)"
11,10,Pb2Ti2O6,TiPbO3,0.000000,"({'Ti': 4.0, 'Pb': 2.0, 'O': -2.0}, {'Ti': 2.0..."
12,11,Pb2Ti2O7,Ti2Pb2O7,0.036364,"({'Ti': 4.0, 'Pb': 3.0, 'O': -2.0}, {'Ti': 3.0..."
13,11,Pb3Ti2O6,Ti2(PbO2)3,0.072727,"({'Ti': 3.0, 'Pb': 2.0, 'O': -2.0}, {'Ti': 2.0..."
14,11,Pb2Ti3O6,Ti3(PbO3)2,0.072727,"({'Ti': 2.6666666666666665, 'Pb': 2.0, 'O': -2..."
15,12,Pb3Ti2O7,Ti2Pb3O7,0.050000,"({'Ti': 4.0, 'Pb': 2.0, 'O': -2.0}, {'Ti': 3.0..."
16,12,Pb2Ti3O7,Ti3Pb2O7,0.050000,"({'Ti': 3.3333333333333335, 'Pb': 2.0, 'O': -2..."
17,12,Pb2Ti2O8,TiPbO4,0.066667,"({'Ti': 4.0, 'Pb': 4.0, 'O': -2.0},)"

In [18]:
test_enumerate_ratio_formulas(chemical_formula = "LiFePO4")

,N,unreduced_formula,reduced_formula,error,ion_guesses
0,6,LiFePO3,LiFePO3,0.071429,"({'Li': 1.0, 'Fe': 2.0, 'P': 3.0, 'O': -2.0},)"
1,7,LiFePO4,LiFePO4,0.000000,"({'Li': 1.0, 'Fe': 2.0, 'P': 5.0, 'O': -2.0}, ..."
2,8,LiFePO5,LiFePO5,0.053571,()
3,8,Li2FePO4,Li2FePO4,0.107143,"({'Li': 1.0, 'Fe': 3.0, 'P': 3.0, 'O': -2.0}, ..."
4,8,LiFeP2O4,LiFe(PO2)2,0.107143,"({'Li': 1.0, 'Fe': 3.0, 'P': 2.0, 'O': -2.0},)"
5,8,LiFe2PO4,LiFe2PO4,0.107143,"({'Li': 1.0, 'Fe': 2.0, 'P': 3.0, 'O': -2.0},)"
6,9,Li2FePO5,Li2FePO5,0.079365,"({'Li': 1.0, 'Fe': 3.0, 'P': 5.0, 'O': -2.0},)"
7,9,LiFe2PO5,LiFe2PO5,0.079365,"({'Li': 1.0, 'Fe': 2.0, 'P': 5.0, 'O': -2.0}, ..."
8,9,LiFeP2O5,LiFeP2O5,0.079365,"({'Li': 1.0, 'Fe': 3.0, 'P': 3.0, 'O': -2.0}, ..."
9,9,LiFePO6,LiFePO6,0.095238,()
10,10,Li2FePO6,Li2FePO6,0.057143,()
11,10,LiFeP2O6,LiFe(PO3)2,0.057143,"({'Li': 1.0, 'Fe': 3.0, 'P': 4.0, 'O': -2.0}, ..."
12,10,LiFe2PO6,LiFe2PO6,0.057143,"({'Li': 1.0, 'Fe': 3.0, 'P': 5.0, 'O': -2.0},)"
13,10,Li2Fe2PO5,Li2Fe2PO5,0.071429,"({'Li': 1.0, 'Fe': 2.5, 'P': 3.0, 'O': -2.0}, ..."
14,10,Li2FeP2O5,Li2FeP2O5,0.071429,"({'Li': 1.0, 'Fe': 2.0, 'P': 3.0, 'O': -2.0},)"
15,10,LiFe2P2O5,LiFe2P2O5,0.071429,"({'Li': 1.0, 'Fe': 3.0, 'P': 1.5, 'O': -2.0}, ..."
16,11,Li2FeP2O6,Li2Fe(PO3)2,0.051948,"({'Li': 1.0, 'Fe': 2.0, 'P': 4.0, 'O': -2.0}, ..."
17,11,Li2Fe2PO6,Li2Fe2PO6,0.051948,"({'Li': 1.0, 'Fe': 2.5, 'P': 5.0, 'O': -2.0}, ..."
18,11,LiFe2P2O6,LiFe2(PO3)2,0.051948,"({'Li': 1.0, 'Fe': 2.5, 'P': 3.0, 'O': -2.0}, ..."
19,11,Li2FePO7,Li2FePO7,0.064935,()
20,11,LiFe2PO7,LiFe2PO7,0.064935,()
21,11,LiFeP2O7,LiFeP2O7,0.064935,"({'Li': 1.0, 'Fe': 3.0, 'P': 5.0, 'O': -2.0},)"
22,12,Li2Fe2PO7,Li2Fe2PO7,0.059524,()
23,12,Li2FeP2O7,Li2FeP2O7,0.059524,"({'Li': 1.0, 'Fe': 2.0, 'P': 5.0, 'O': -2.0}, ..."
24,12,LiFe2P2O7,LiFe2P2O7,0.059524,"({'Li': 1.0, 'Fe': 2.5, 'P': 4.0, 'O': -2.0}, ..."
25,12,Li2Fe2P2O6,LiFePO3,0.071429,"({'Li': 1.0, 'Fe': 2.0, 'P': 3.0, 'O': -2.0},)"

In [19]:
test_enumerate_ratio_formulas(chemical_formula = "LiFeO2")

,N,unreduced_formula,reduced_formula,error,ion_guesses
0,4,LiFeO2,LiFeO2,0.000000,"({'Li': 1.0, 'Fe': 3.0, 'O': -2.0},)"
1,5,LiFeO3,LiFeO3,0.100000,()
2,6,Li2FeO3,Li2FeO3,0.083333,()
3,6,LiFe2O3,LiFe2O3,0.083333,"({'Li': 1.0, 'Fe': 2.5, 'O': -2.0},)"
4,7,Li2Fe2O3,Li2Fe2O3,0.071429,"({'Li': 1.0, 'Fe': 2.0, 'O': -2.0},)"
5,7,LiFe2O4,Li(FeO2)2,0.107143,()
6,7,Li2FeO4,Li2FeO4,0.107143,()
7,8,Li2Fe2O4,LiFeO2,0.000000,"({'Li': 1.0, 'Fe': 3.0, 'O': -2.0},)"
8,9,Li2Fe2O5,Li2Fe2O5,0.055556,()
9,9,Li2Fe3O4,Li2Fe3O4,0.083333,"({'Li': 1.0, 'Fe': 2.0, 'O': -2.0},)"
10,9,Li3Fe2O4,Li3(FeO2)2,0.083333,"({'Li': 1.0, 'Fe': 2.5, 'O': -2.0},)"
11,10,Li2Fe3O5,Li2Fe3O5,0.050000,"({'Li': 1.0, 'Fe': 2.6666666666666665, 'O': -2..."
12,10,Li3Fe2O5,Li3Fe2O5,0.050000,()
13,10,Li2Fe2O6,LiFeO3,0.100000,()
14,11,Li3Fe3O5,Li3Fe3O5,0.045455,"({'Li': 1.0, 'Fe': 2.3333333333333335, 'O': -2..."
15,11,Li2Fe3O6,Li2(FeO2)3,0.068182,()
16,11,Li3Fe2O6,Li3(FeO3)2,0.068182,()
17,12,Li3Fe3O6,LiFeO2,0.000000,"({'Li': 1.0, 'Fe': 3.0, 'O': -2.0},)"

In [20]:
test_enumerate_ratio_formulas(chemical_formula = "Li2FeO3")

,N,unreduced_formula,reduced_formula,error,ion_guesses
0,5,Li2FeO2,Li2FeO2,0.100000,"({'Li': 1.0, 'Fe': 2.0, 'O': -2.0},)"
1,6,Li2FeO3,Li2FeO3,0.000000,()
2,7,Li2FeO4,Li2FeO4,0.071429,()
3,7,Li3FeO3,Li3FeO3,0.095238,"({'Li': 1.0, 'Fe': 3.0, 'O': -2.0},)"
4,7,Li2Fe2O3,Li2Fe2O3,0.119048,"({'Li': 1.0, 'Fe': 2.0, 'O': -2.0},)"
5,8,Li3FeO4,Li3FeO4,0.041667,()
6,8,Li2Fe2O4,LiFeO2,0.083333,"({'Li': 1.0, 'Fe': 3.0, 'O': -2.0},)"
7,8,Li2FeO5,Li2FeO5,0.125000,()
8,9,Li3Fe2O4,Li3(FeO2)2,0.055556,"({'Li': 1.0, 'Fe': 2.5, 'O': -2.0},)"
9,9,Li3FeO5,Li3FeO5,0.055556,()
10,9,Li4FeO4,Li4FeO4,0.111111,()
11,10,Li3Fe2O5,Li3Fe2O5,0.033333,()
12,10,Li4FeO5,Li4FeO5,0.066667,()
13,10,Li3FeO6,Li3FeO6,0.100000,()
14,11,Li4Fe2O5,Li4Fe2O5,0.045455,"({'Li': 1.0, 'Fe': 3.0, 'O': -2.0},)"
15,11,Li3Fe2O6,Li3(FeO3)2,0.060606,()
16,11,Li4FeO6,Li4FeO6,0.075758,()
17,12,Li4Fe2O6,Li2FeO3,0.000000,()

In [21]:
test_enumerate_ratio_formulas(chemical_formula = "Li2O2")

     N unreduced_formula reduced_formula     error ion_guesses
0    2               LiO           Li2O2  0.000000          ()
1    4             Li2O2           Li2O2  0.000000          ()
2    5             Li2O3           Li2O3  0.100000          ()
3    5             Li3O2           Li3O2  0.100000          ()
4    6             Li3O3           Li2O2  0.000000          ()
5    7             Li3O4           Li3O4  0.071429          ()
6    7             Li4O3           Li4O3  0.071429          ()
7    8             Li4O4           Li2O2  0.000000          ()
8    9             Li4O5           Li4O5  0.055556          ()
9    9             Li5O4           Li5O4  0.055556          ()
10  10             Li5O5           Li2O2  0.000000          ()
11  11             Li5O6           Li5O6  0.045455          ()
12  11             Li6O5           Li6O5  0.045455          ()
13  12             Li6O6           Li2O2  0.000000          ()

In [22]:
test_enumerate_ratio_formulas(chemical_formula = "LiO8")

     N unreduced_formula reduced_formula     error    ion_guesses
0    5              LiO4            LiO4  0.088889             ()
1    6              LiO5            LiO5  0.055556             ()
2    6                O6              O2  0.111111  ({'O': 0.0},)
3    7              LiO6            LiO6  0.031746             ()
4    7                O7              O2  0.111111  ({'O': 0.0},)
5    8              LiO7            LiO7  0.013889             ()
6    8                O8              O2  0.111111  ({'O': 0.0},)
7    9              LiO8            LiO8  0.000000             ()
8   10              LiO9            LiO9  0.011111             ()
9   10             Li2O8            LiO4  0.088889             ()
10  11             LiO10           LiO10  0.020202             ()
11  11             Li2O9           Li2O9  0.070707             ()
12  12             LiO11           LiO11  0.027778             ()
13  12            Li2O10            LiO5  0.055556             ()

In [23]:
test_enumerate_ratio_formulas(chemical_formula = "Ni3Pt")

     N unreduced_formula reduced_formula     error ion_guesses
0    4             Ni3Pt           Ni3Pt  0.000000          ()
1    5             Ni4Pt           Ni4Pt  0.050000          ()
2    6            Ni4Pt2           Ni2Pt  0.083333          ()
3    6             Ni5Pt           Ni5Pt  0.083333          ()
4    7            Ni5Pt2          Ni5Pt2  0.035714          ()
5    7             Ni6Pt           Ni6Pt  0.107143          ()
6    8            Ni6Pt2           Ni3Pt  0.000000          ()
7    9            Ni7Pt2          Ni7Pt2  0.027778          ()
8    9            Ni6Pt3           Ni2Pt  0.083333          ()
9   10            Ni8Pt2           Ni4Pt  0.050000          ()
10  10            Ni7Pt3          Ni7Pt3  0.050000          ()
11  11            Ni8Pt3          Ni8Pt3  0.022727          ()
12  11            Ni9Pt2          Ni9Pt2  0.068182          ()
13  12            Ni9Pt3           Ni3Pt  0.000000          ()

In [24]:
test_enumerate_ratio_formulas(chemical_formula = "NiPt")

     N unreduced_formula reduced_formula     error ion_guesses
0    2              NiPt            NiPt  0.000000          ()
1    4            Ni2Pt2            NiPt  0.000000          ()
2    5            Ni2Pt3          Ni2Pt3  0.100000          ()
3    5            Ni3Pt2          Ni3Pt2  0.100000          ()
4    6            Ni3Pt3            NiPt  0.000000          ()
5    7            Ni3Pt4          Ni3Pt4  0.071429          ()
6    7            Ni4Pt3          Ni4Pt3  0.071429          ()
7    8            Ni4Pt4            NiPt  0.000000          ()
8    9            Ni4Pt5          Ni4Pt5  0.055556          ()
9    9            Ni5Pt4          Ni5Pt4  0.055556          ()
10  10            Ni5Pt5            NiPt  0.000000          ()
11  11            Ni5Pt6          Ni5Pt6  0.045455          ()
12  11            Ni6Pt5          Ni6Pt5  0.045455          ()
13  12            Ni6Pt6            NiPt  0.000000          ()